all:
	date

run-10devices:
	for i in `seq 1 10`; do echo $i; bash -c 'ruby input_device_simulator.rb & '; done

run-100devices:
	for i in `seq 1 100`; do echo $i; bash -c 'ruby input_device_simulator.rb & '; done

run-250devices:
	for i in `seq 1 250`; do echo $i; bash -c 'ruby input_device_simulator.rb & '; done

