all:
	date

run-1devices:
	for i in `seq 1 1`; do bash -c 'ruby input_device_simulator.rb & '; done

run-10devices:
	for i in `seq 1 10`; do bash -c 'ruby input_device_simulator.rb & '; done

run-100devices:
	for i in `seq 1 100`; do bash -c 'ruby input_device_simulator.rb & '; done

run-250devices:
	for i in `seq 1 250`; do bash -c 'ruby input_device_simulator.rb & '; done

